parameters:
    gsf_user.securityauthenticationlistener_class:  GollumSF\UserBundle\Security\Firewall\UserListener
    gsf_user.listener_insufficientauthentication_class: GollumSF\UserBundle\EventListener\InsufficientAuthenticationListener
    gsf_user.listener_logger_subscriber_class: GollumSF\UserBundle\EventListener\LoggerSubscriber
services:
    
    gsf_user.security.authentication_listener:
        class: '%gsf_user.securityauthenticationlistener_class%'
        arguments:
            - '@security.token_storage'
            - '@security.authentication.manager'
        public: false
    
    gsf_user.listener.insufficient_authentication:
        class: "%gsf_user.listener_insufficientauthentication_class%"
        arguments:
            - '@security.token_storage'
            - '@router'
            - '@gsf_user.parameter.url_selector'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    
    gsf_user.listener.logger_subscriber:
        class: "%gsf_user.listener_logger_subscriber_class%"
        arguments:
            - '@logger'
        tags:
            - { name: kernel.event_subscriber }
    