parameters:
    gsf_user.parameter_twigselector_class: GollumSF\UserBundle\Parameter\ParameterSelector
    gsf_user.parameter_formselector_class: GollumSF\UserBundle\Parameter\ParameterSelector

services:
    
    gsf_user.manager.user:
        class: "%gsf_user.configurations.user.manager%"
        calls:
            - [setEntityManager, ['@doctrine.orm.entity_manager']]
            - [setEntityClass  , ['%gsf_user.configurations.user.entity%']]
    
    gsf_user.parameter.twig_selector:
        class: "%gsf_user.parameter_twigselector_class%"
        arguments:
            - '@service_container'
            - 'gsf_user.configurations.form'
    
    gsf_user.parameter.form_selector:
        class: "%gsf_user.parameter_formselector_class%"
        arguments:
            - '@service_container'
            - 'gsf_user.configurations.twig'