parameters:
    gsf_user.securityauthenticationprovider_class: GollumSF\UserBundle\Security\Authentication\Provider\UserAuthenticationProvider
    gsf_user.authenticator_class: GollumSF\UserBundle\Authenticator\Authenticator
    gsf_user.parameter_twigselector_class: GollumSF\UserBundle\Parameter\ParameterSelector
    gsf_user.parameter_formselector_class: GollumSF\UserBundle\Parameter\ParameterSelector
services:
    
    gsf_user.security.authentication_provider:
        class: '%gsf_user.securityauthenticationprovider_class%'
        arguments:
            - '@gsf_user.manager.user'
        public: false
    
    gsf_user.authenticator:
        class: "%gsf_user.authenticator_class%"
        arguments:
            - '@security.token_storage'
            - '%secret%'
            - '@request_stack'
            - '@event_dispatcher'
    
    gsf_user.parameter.twig_selector:
        class: "%gsf_user.parameter_twigselector_class%"
        arguments:
            - '@service_container'
            - 'gsf_user.configurations.form'
    
    gsf_user.parameter.form_selector:
        class: "%gsf_user.parameter_formselector_class%"
        arguments:
            - '@service_container'
            - 'gsf_user.configurations.twig'
    
    gsf_user.parameter.url_selector:
        class: "%gsf_user.parameter_formselector_class%"
        arguments:
            - '@service_container'
            - 'gsf_user.configurations.url'